import streamlit as st
import asyncio
import time
import os
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types as genai_types
from agent.agent import create_greeting_agent
from constants import APP_NAME_FOR_ADK, USER_ID, INITIAL_STATE, ADK_SESSION_KEY

import asyncio
import os
import time
import streamlit as st
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from agent.agent import create_greeting_agent
from constants import APP_NAME_FOR_ADK, USER_ID, INITIAL_STATE, ADK_SESSION_KEY

@st.cache_resource
def get_session_service():
    return InMemorySessionService()

@st.cache_resource
def get_runner():
    root_agent = create_greeting_agent()
    session_service = get_session_service()
    return Runner(agent=root_agent, app_name=APP_NAME_FOR_ADK, session_service=session_service)

def initialize_adk():
    runner = get_runner()
    session_service = runner.session_service

    if ADK_SESSION_KEY not in st.session_state:
        session_id = f"streamlit_adk_session_{int(time.time())}_{os.urandom(4).hex()}"
        st.session_state[ADK_SESSION_KEY] = session_id

        # ✅ create_session is async, so run it properly
        asyncio.run(session_service.create_session(
            app_name=APP_NAME_FOR_ADK,
            user_id=USER_ID,
            session_id=session_id,
            state=INITIAL_STATE
        ))
    else:
        session_id = st.session_state[ADK_SESSION_KEY]
        # Verify session still exists
        session = asyncio.run(session_service.get_session(
            app_name=APP_NAME_FOR_ADK,
            user_id=USER_ID,
            session_id=session_id
        ))
        if not session:
            asyncio.run(session_service.create_session(
                app_name=APP_NAME_FOR_ADK,
                user_id=USER_ID,
                session_id=session_id,
                state=INITIAL_STATE
            ))

    return runner, session_id

async def run_adk_async(runner: Runner, session_id: str, user_message_text: str):
    """
    Asynchronously runs a single turn of the ADK agent conversation.
    """
    session = runner.session_service.get_session(app_name=APP_NAME_FOR_ADK, user_id=USER_ID, session_id=session_id)
    if not session:
        return "Error: ADK session not found."
    # Prepare the user's message in the format expected by ADK/Gemini.
    content = genai_types.Content(role='user', parts=[genai_types.Part(text=user_message_text)])
    final_response_text = "[Agent encountered an issue]" # Default error message
    # Iterate through the asynchronous events generated by the ADK runner.
    # ADK can yield multiple events (e.g., tool calls, interim responses) before the final response.

    tool_placeholder = None

    async for event in runner.run_async(user_id=USER_ID, session_id=session_id, new_message=content):
        
        # TOOL CALL (show loader)
        if event.get_function_calls():
            for fc in event.get_function_calls():
                if tool_placeholder is None:
                    tool_placeholder = st.empty()
                with tool_placeholder.container():
                    st.chat_message("assistant").markdown(f"⚙️ Calling tool: **{fc.name}** ...")

        # TOOL RESPONSE (replace loader with success)
        elif event.get_function_responses():
            for fr in event.get_function_responses():
                if tool_placeholder:
                    tool_placeholder.empty()  # clear loader
                    tool_placeholder = None
                with st.chat_message("assistant"):
                    st.success(f"✅ Tool response received for **{fr.name}**")

        # FINAL AGENT RESPONSE
        elif event.is_final_response():
            if event.content and event.content.parts and hasattr(event.content.parts[0], "text"):
                final_response_text = event.content.parts[0].text
                if tool_placeholder:
                    tool_placeholder.empty()  # remove loader if still there
                    tool_placeholder = None
                # with st.chat_message("assistant"):
                #     st.markdown(final_response_text)
            break
    return final_response_text
def run_adk_sync(runner: Runner, session_id: str, user_message_text: str) -> str:
    """
    Synchronous wrapper for running ADK, as Streamlit does not directly support async calls in the main thread.
    """
    # Runs the asynchronous function in a new event loop.
    return asyncio.run(run_adk_async(runner, session_id, user_message_text))