LLM_MODEL="gemini-2.5-flash"

ROOT_AGENT_MODEL=LLM_MODEL
NEO4J_TOOL_MODEL=LLM_MODEL
MONGO_TOOL_MODEL="gemini-2.5-flash-lite"
TTS_MINI_LLM_MODEL="gemini-2.5-flash-lite"

ROOT_AGENT_TEMPERATURE=0.1
NEO4J_TOOL_TEMPERATURE=0.1
MONGO_TOOL_TEMPERATURE=0.1

ENABLE_TTS = False

APP_NAME_FOR_ADK = "Product Recommender App" 
USER_ID = "fatima" 

INITIAL_STATE = {}


MESSAGE_HISTORY_KEY = "messages_final_mem_v2" 
ADK_SESSION_KEY = "adk_session_id" 
